package com.jennysival.nookapp.utils

const val NOOKAPP_MISSOES = "Missões Diárias"
const val NOOKAPP_CONQUISTAS = "Conquistas"
const val NOOKAPP_CRIATURAS = "Criaturas"
const val NOOKAPP_RECEITAS = "Receitas"
const val NOOKAPP_CATALOGO = "Catalogo"
const val NOOKAPP_VISITANTES = "Visitantes e Moradores"
const val NOOKAPP_MINHA_ILHA = "Minha Ilha"
const val NOOKAPP_MUSICAS = "Músicas"
const val NOOKAPP_AMIGOS = "Amigos"
const val NOOKAPP_FINANCAS = "Finanças"
const val NOOKAPP_FLORES = "Flores"
const val NOOKAPP_SOBRE = "Sobre o App"
const val NOOKAPP_AGENDA = "Agenda"
const val NOOKAPP_FOSSEIS = "Fósseis"
const val NOOKAPP_GYROIDS = "Gyroids"

const val NOOKAPP_FEAT_KEY = "FEAT_KEY"
const val NOOKAPP_API_ERROR_MESSAGE = "Ops! Tente novamente mais tarde"